In [22]:
# ** Excel Processing **

In [24]:
# Variables
data_folder = 'lokad'
filenames = {'items': data_folder+'/Lokad_Items.xls'}

# ** Read Excel sheet **

In [21]:
import sys
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile

try:
    items = pd.read_excel('lokad/Lokad_Items.xls', sheetname='Lokad_Items')
except:
    print("Error: "+str(sys.exc_info()[1]))

try:
    bom = pd.read_excel('lokad/Lokad_BOM.xls', sheetname='Lokad_BOM')
except:
    print("Error: "+str(sys.exc_info()[1]))
 

print("Column headings:")
print(df.columns)

ids = df['Id']
names = df['Name']

print('IDs: '+str(len(ids)))
print('Names: '+str(len(names)))

Column headings:
Index(['Id', 'Loc', 'Ref', 'Name', 'Category', 'SubCategory', 'Brand',
       'Supplier', 'StockOnHand', 'StockOnOrder', 'BackOrder', 'BuyPrice',
       'SellPrice', 'MOQ', 'LotMultiplier', 'Volume'],
      dtype='object')
IDs: 318
Names: 318

# ** Read File entirely **

In [38]:
import sys
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile

items_xls = pd.ExcelFile('lokad/Lokad_Items.xls')
items = items_xls.parse('Lokad_Items')

bom_xls = pd.ExcelFile('lokad/Lokad_BOM.xls')
bom = bom_xls.parse('Lokad_BOM')

In [39]:
print(items.shape)
items.head(10)

(318, 16)

,Id,Loc,Ref,Name,Category,SubCategory,Brand,Supplier,StockOnHand,StockOnOrder,BackOrder,BuyPrice,SellPrice,MOQ,LotMultiplier,Volume
0,10014552/Chicago,Chicago,10014552,Belkin 8 Outlet SurgeMaster II Gold Surge Prot...,Office Supplies,Appliances,Belkin,FHL,6,0,0,7.370000,17.180000,0,20,0.045028
1,10014552/Los Angeles,Los Angeles,10014552,Belkin 8 Outlet SurgeMaster II Gold Surge Prot...,Office Supplies,Appliances,Belkin,FHL,3,3,2,7.370000,17.180000,0,20,0.045028
2,10014552/New-York,New-York,10014552,Belkin 8 Outlet SurgeMaster II Gold Surge Prot...,Office Supplies,Appliances,Belkin,FHL,0,10,0,7.370000,17.180000,0,20,0.045028
3,10095232/Chicago,Chicago,10095232,Hoover WindTunnel Plus Canister Vacuum,Office Supplies,Appliances,Hoover,Office First,0,0,0,26.680000,51.680000,0,0,0.098302
4,10095232/Los Angeles,Los Angeles,10095232,Hoover WindTunnel Plus Canister Vacuum,Office Supplies,Appliances,Hoover,Office First,0,0,0,26.680000,51.680000,0,0,0.098302
5,10095232/New-York,New-York,10095232,Hoover WindTunnel Plus Canister Vacuum,Office Supplies,Appliances,Hoover,Office First,80,0,0,26.680000,51.680000,0,0,0.098302
6,10099950/Chicago,Chicago,10099950,Staples 4 Outlet Surge Protector,Office Supplies,Appliances,Staples,Logipro,4,20,0,33.060001,50.040001,0,2,0.005964
7,10099950/Los Angeles,Los Angeles,10099950,Staples 4 Outlet Surge Protector,Office Supplies,Appliances,Staples,Logipro,0,0,0,33.060001,50.040001,0,2,0.005964
8,10099950/New-York,New-York,10099950,Staples 4 Outlet Surge Protector,Office Supplies,Appliances,Staples,Logipro,45,40,0,33.060001,50.040001,0,2,0.005964
9,10132892/Chicago,Chicago,10132892,"Acco Pressboard Covers with Storage Hooks, 14 ...",Office Supplies,Binders and Binder Accessories,Acco,Drecom,21,0,0,46.380001,67.750000,0,4,0.069723

In [45]:
# Column data
item_ids = items['Id']
item_ids.head(10)

0        10014552/Chicago
1    10014552/Los Angeles
2       10014552/New-York
3        10095232/Chicago
4    10095232/Los Angeles
5       10095232/New-York
6        10099950/Chicago
7    10099950/Los Angeles
8       10099950/New-York
9        10132892/Chicago
Name: Id, dtype: object

In [40]:
print(bom.shape)
bom.head(10)

(14, 3)

     Bundle      Part  Quantity
0  13336895  13452029         1
1  13336895  13934616         3
2  14802650  14789055         1
3  14802650  15092233         1
4  14802650  15431986         1
5  14802650  15641711         1
6  13944445  13934616         1
7  13944445  13908259         1
8  11711150  11711636         3
9  14993287  14895172         1

In [82]:
%timeit new = item_ids.str.split('/',1, expand=True)

In [84]:
type(items_xls)

pandas.io.excel.ExcelFile

In [ ]:
# identify spaces in front using regex
# identify trailing spaces
# identify double spaces
# reduce multiple spaces to single space
# left join two pandas tables
# compute total cost of the bom
# plot histogram of bom prices
# do a scatter plot of two features as a demonstration of correlation e.g. part vs price